### ISSUE TITLE
Convert to Swift 5

### ISSUE THREAD

**Issue by awhitford** [DarshanGowda0/GeoFlutterFire#101]
XCode gives me a _Buildtime Warning_ saying that `geoflutterfire.framework` may be converted to Swift 5.

Any chance that this can be upgraded so that this warning goes away?

**Comment by awhitford** [comment]
I'm pretty sure it is referring to this project:
https://github.com/DarshanGowda0/GeoFlutterFire/blob/7f4c29db3072b2a56b27e582038392eea2deb8b2/ios/geoflutterfire.podspec#L8

Having said that, perhaps the best approach would be to purge the Swift code (and Kotlin code for Android) altogether because there is nothing native going on here.  Since the code is all Dart, this doesn't need android & ios specific code.  This change would ultimately be better because it is automatically multi-platform.

**Comment by awhitford** [comment]
When you created the project, you had a choice to create a `plugin` or a `package`, and you chose `plugin`, but you really needed a `package`:
 * `package` - Generate a shareable Flutter project containing modular Dart code.
 * `plugin` - Generate a shareable Flutter project containing an API in Dart code with a platform-specific implementation for Android, for iOS code, or for both.

**Comment by DarshanGowda0** [comment]
Yep, this makes sense. I'll see what I can do
