### ISSUE TITLE
No Data

### ISSUE THREAD

**Issue by dupiesdupreez** [DarshanGowda0/GeoFlutterFire#106]
The query does not yield any results.

```
 GeoFirePoint center =
        _geo.point(latitude: -26.015461, longitude: 20);

    double radius = 5; //KM
    String field = 'pickupLocation';

    Stream<List<DocumentSnapshot>> stream = _geo
        .collection(collectionRef: Firestore.instance.collection('workers'))
        .within(center: center, radius: radius, field: field);

    stream.listen((List<DocumentSnapshot> documentList) {
      var x = documentList; --> (0 elements)
    })
```

![image](https://user-images.githubusercontent.com/6910085/86786504-6317fb00-c064-11ea-8847-ee240430681f.png)

**Comment by webertim** [comment]
Not sure if this will change anything, but in my Firestore the field names are 'geohash' and 'geopoint' instead of 'geoHash' and 'geoPoint'

**Comment by dupiesdupreez** [comment]
@webertim YOU Tim, saved me after wasting 3 HOURS of my life. 

Just wanted to thank you for taking the time out of your day to help me out. That was Exactly the problem!

Thanks Tim

**Comment by webertim** [comment]
@dupiesdupreez Very happy to hear that :) Have a nice day!
