### ISSUE TITLE
Collection Stream causes spawning of several snapshot listeners

### ISSUE THREAD

**Issue by JustChris** [DarshanGowda0/GeoFlutterFire#108]
There still seems to be a problem. When I use StreamBuilder or any other stream subscription with the following stream:

`geoflutterfire
          .collection(collectionRef: Firestore.instance.collection(collectionPath))
          .within(
            center: center,
            radius: radius,
            field: 'position',
            strictMode: true,
          );`

There are 9 snapshot listeners spawning. You can see that in the monitoring section of console.cloud.google.com. It is always 9! Why?

![screenshot-console cloud google com-2020 07 22-20_02_10](https://user-images.githubusercontent.com/68645707/88211779-79be7480-cc56-11ea-9851-dab6a233215d.png)

Thanks.

_Originally posted by @JustChris in https://github.com/DarshanGowda0/GeoFlutterFire/issues/13#issuecomment-662413515_

**Comment by awhitford** [comment]
Maybe seeing your code will help resolve this.  I suspect it is a widget lifecycle issue.
