### ISSUE TITLE
GeoFireCollectionRef.data(id) looks suspicious

### ISSUE THREAD

**Issue by awhitford** [DarshanGowda0/GeoFlutterFire#113]
I was just reviewing the code and this does not look correct:

https://github.com/DarshanGowda0/GeoFlutterFire/blob/12340796b2f095ec935864a88ca9df5617afb19d/lib/src/collection.dart#L23-L31

Lines 26-28 are basically a _no-op_ because the `where` function returns an `Iterable` that is ignored.  And ultimately, the `id` parameter is ignored.

(You might consider removing this function altogether.)

**Comment by awhitford** [comment]
PR #121 resolves this.

**Comment by awaik** [comment]
Commit merged with 3x_null_safety branch.
