### ISSUE TITLE
Is it possible to limit max quarry range with security rules?

### ISSUE THREAD

**Issue by LetsUpdate** [DarshanGowda0/GeoFlutterFire#114]
I dont wanna to some hacker like guy dump all of the locations from the db with a single quarry
Is there any solution fo this?

**Comment by cngeru** [comment]
I have created a new library that works almost like `GeoFlutterFire` which gives you more control on how you do your queries. Please check it out [https://pub.dev/packages/georange](https://pub.dev/packages/georange)
