### ISSUE TITLE
Plans on limit()?

### ISSUE THREAD

**Issue by JustChris** [DarshanGowda0/GeoFlutterFire#117]
Do you plan on implementing a proper limit functionality? That would be a GREAT feature for everyone!
Thanks!

**Comment by jesusrb89** [comment]
and order by time also!

**Comment by Matthuffy** [comment]
I think Limit and orderby are absolutely crucial unless you have extremely small data.

**Comment by Matthuffy** [comment]
I have simply added .limit(10) to the _queryPoint() and it is working fine.

**Comment by JustChris** [comment]
@DarshanGowda0 Can you confirm this and implement this solution into a new version?

**Comment by Matthuffy** [comment]
Already have, will be testing a few more edits over the coming days.

**Comment by Matthuffy** [comment]
https://github.com/Matthuffy/GeoFlutterFire

**Comment by JustChris** [comment]
Thanks! Did you create a pull request?

**Comment by Matthuffy** [comment]
Not yet, have a ton of other changes to make before that. Just really busy right now for a couple of weeks with couple of projects.

**Comment by Matthuffy** [comment]
Since I will be that busy, went ahead and make PR.

**Comment by JustChris** [comment]
I tested it by just adding limit to `endAt`. It doesn’t seem to work properly. My returned element list gets cut at the wrong end.

For example:

A list of three elements is returned. 1, 2 and 3 meters.
When I set limit to two, always the nearest element disappears. This case 1 meter.
I want that the other way around. I want the farthest elements to get cut off the list.

When I try to change the `orderBy`, nothing is returned any more at all.

Can you confirm this @DarshanGowda0 ?

**Comment by Engelbrekt39** [comment]
> 
> 
> Not yet, have a ton of other changes for better edits on the orderby to make before that. Just really busy right now for a couple of weeks with couple of projects.
> 
> Just copy the /lib files to a project and mess with it.
> 
> Also when you limit, you will want to most probably also show the next X results and there are a few ways to do that depending on your needs, so for now keeping it separate for that reason to

I think the limit by works pretty well and can't believe I didn't try and do that myself,  I just assumed it wouldn't work. So thanks a lot for doing it!

As for getting the next documents after our set limit. How would you do that in this case? Would you be able to point me to an example or provide any other pointers?

**Comment by naveenbharadwaj19** [comment]
Can i use limit in `geo.collection(collectionRef : collectionRef , limit : 10)` ?
geoflutterfire version : `2.2.1`

**Comment by zzterrozz** [comment]
> Not yet, have a ton of other changes for better edits on the orderby to make before that. Just really busy right now for a couple of weeks with couple of projects.
> 
> Just copy the /lib files to a project and mess with it.
> 
> Also when you limit, you will want to most probably also show the next X results and there are a few ways to do that depending on your needs, so for now keeping it separate for that reason to

The link to the repo is dead. Any chance you push the PR in order to get the `limit` in queries please ?

**Comment by willbouch** [comment]
@DarshanGowda0 Hello, would like to know what is the status for the `limit` in queries please ?

**Comment by cngeru** [comment]
I have created a new library that works almost like `GeoFlutterFire` which gives you more control on how you do your queries. Please check it out [https://pub.dev/packages/georange](https://pub.dev/packages/georange)
