### ISSUE TITLE
Contribution

### ISSUE THREAD

**Issue by HossamElharmeil** [DarshanGowda0/GeoFlutterFire#119]
Thanks a ton for the great work on this library! Is there any policy for contributing? I couldn't find any files in the repo for contribution guidelines and I would love to contribute if you accept that

**Comment by awhitford** [comment]
I am not the project owner, but the project does accept pull requests.

**Comment by HossamElharmeil** [comment]
Yea just noticed, awhitford. Thanks for the tip!
