### ISSUE TITLE
Substreams of surrounding 9 geohashes do not get disposed 

### ISSUE THREAD

**Issue by JustChris** [DarshanGowda0/GeoFlutterFire#130]
When I am listening to the `within` stream, the plugin creates 9 streams for the nearby geohashes.
When I dispose the stream to the `within` subscription, the 9 substreams should also be disposed, but this is not happening.

Could this not lead to memory leaks??

**Comment by JustChris** [comment]
I think I figured out why this is. 

I am using the resulting stream in a behaviorSubject which is a broadcast controller.
Since the resulting stream is return as a broadcast stream as well, the source streams are not going to be closed when I cancel the stream subscription of that behaviorSubject for some reason.

The solution for me was to simply removing the `asBroadcastStream()` in file `collection.dart`.

**Comment by talmr-k** [comment]
This still happens for me. Any solution to this?
