### ISSUE TITLE
Where condition not working, without that plugin is not usefull , please fix asap.

### ISSUE THREAD

**Issue by krsolutions** [DarshanGowda0/GeoFlutterFire#132]
Where condition not working, without that plugin is not usefull , please fix asap.

**Comment by luantrasel** [comment]
it is working for me on version 2.2.1

you just need to add the where condition in the query that you pass to the collectionRef parameter

```
final collection = FirebaseFirestore.instance
        .collection('locations')
        .where('city', isEqualTo: 'San Francisco');

    Stream<List<DocumentSnapshot>> stream = Geoflutterfire()
        .collection(collectionRef: collection)
        .within(
            center: GeoFirePoint(40.7651, -73.9692633),
            radius: 40,
            field: 'location');
```

**Comment by krsolutions** [comment]
We need to register a composite query to make it work, for example, if there are filters like brands, size, gender...etc

we need to create an index for all combinations Nike, xl, male & puma, l, female ..etc

**Comment by awaik** [comment]
@krsolutions 
Have you solved this issue?

**Comment by huangkaichang** [comment]
@awaik I am having the issue too, when put in the where condition, it stops working.

**Comment by huangkaichang** [comment]
Solved the issue too by adding a composite query. https://github.com/DarshanGowda0/GeoFlutterFire/issues/99#issuecomment-778756666
