### ISSUE TITLE
update dependencies

### ISSUE THREAD

**Issue by awaik** [DarshanGowda0/GeoFlutterFire#133]
Thank you for the great plugin!
Can you please update?

_Because geoflutterfire 2.2.1 depends on cloud_firestore ^0.14.0+2 and no versions of geoflutterfire match >2.2.1 <3.0.0, geoflutterfire ^2.2.1 requires cloud_firestore ^0.14.0+2.
So, because app depends on both cloud_firestore ^0.15.0 and geoflutterfire ^2.2.1, version solving failed.
pub get failed (1; So, because app depends on both cloud_firestore ^0.15.0 and geoflutterfire ^2.2.1, version solving failed.)_

**Comment by jonbhanson** [comment]
I'd like to see the dependancies updated as well.  👍🏻🙏🏻

**Comment by wilpar** [comment]
definitely blocking updates of Cloud Firestore, cloud functions, firebase auth.

**Comment by wilpar** [comment]
Pull Request created:
https://github.com/DarshanGowda0/GeoFlutterFire/pull/136

**Comment by awaik** [comment]
For those who can't wait like me.

Just the temporary decision while we awaiting developers' update package - I made a branch and updated dependencies. You can use it in your pubspec.yaml

```
#  geoflutterfire: ^2.2.1
  geoflutterfire:
    git:
      url: https://github.com/awaik/GeoFlutterFire
```

After updates available here, don't forget switch back to the main version :)

**Comment by jonbhanson** [comment]
@awaik thanks for the stop-gap solution.  Could you also update the rxdart dependency in your repo to ^0.25.0?

**Comment by awaik** [comment]
> @awaik thanks for the stop-gap solution. Could you also update the rxdart dependency in your repo to ^0.25.0?

done

**Comment by jonbhanson** [comment]
Thanks 🤘

**Comment by giorgio79** [comment]
@awaik  can you please up cloud firestore to 0.17? :)

**Comment by awaik** [comment]
@giorgio79 the latest version is 0.16.0+1
https://pub.dev/packages/cloud_firestore/versions

**Comment by giorgio79** [comment]
Sorry, I meant 1.0

**Comment by awaik** [comment]
This is a preview version. 
For this case better make a fork and change it yourself.

**Comment by jonbhanson** [comment]
I sent an email last week to @DarshanGowda0 to see if he would like help maintaining this plugin or someone to take  it over, but I did not get a response yet. 😕

**Comment by awaik** [comment]
Yes,
it looks like there is no support anymore.
I think, when null safety comes,  it would be great,  to create a copy of this package with credits for authors and live support.
Because, with null safety, it will demand significant changes.

**Comment by vishnuagbly** [comment]
@awaik I think this is the right time to create a copy of this package with also the announcement of flutter 2, this would help a lot of people. I think currently you and @zeusbaba can be the maintainers

**Comment by jonbhanson** [comment]
My null-safe fork can be found [here](https://github.com/jonbhanson/GeoFlutterFire).  It is a work in progress, so please let me know about any problem you run into.

To run it, add to your `pubspec.yaml`:

```yaml
geoflutterfire:
    git: git://github.com/jonbhanson/GeoFlutterFire.git
```

I will publish it to pub.dev soon.

**Comment by vishnuagbly** [comment]
Currently, there are more than 4 forked versions of this library, We are currently thinking to create a single temporary forked or copied version of the repo to work on further development. Anyone who wants to contribute is welcome to join our [Discord Group](https://discord.gg/PWGGgXMv) made for discussion.

**Comment by DarshanGowda0** [comment]
Hey everyone!

Sorry for not updating this dependency for a while! I’ve been really busy with my graduate studies and have no time to allocate for this project! I’ve added @awaik as a maintainer to this project now, please do send a mail to me personally if anyone else wants to be a maintainer!

I apologize for all the fuzz again!

**Comment by Enqvida** [comment]
Thank you @awaik for taking the time to support the project!

**Comment by aadie13** [comment]
GeoFlutterFire does not yet have an updated dependency. Any updates on the progress?
