### ISSUE TITLE
GeoFlutterFire is not supporting cloud_firestore ^0.16.0

### ISSUE THREAD

**Issue by deepaknssd** [DarshanGowda0/GeoFlutterFire#137]
GeoFlutterFire is not supporting cloud_firestore ^0.16.0

**Comment by sammy44nts** [comment]
👍🏽

**Comment by anirudhsharma392** [comment]
Did you find any solution to it ?

**Comment by jonbhanson** [comment]
[Interim solution](https://github.com/DarshanGowda0/GeoFlutterFire/issues/133#issuecomment-762029201)

**Comment by deepaknssd** [comment]
Thanks, :)

**Comment by vishnuagbly** [comment]
Currently, there are more than 4 forked versions of this library, We are currently thinking to create a single temporary forked or copied version of the repo to work on further development. Anyone who wants to contribute is welcome to join our [Discord Group](https://discord.gg/PWGGgXMv) made for discussion.

**Comment by awaik** [comment]
fixed, update online on the https://pub.dev/packages/geoflutterfire
