### ISSUE TITLE
GeoFlutterFire v2.2.1 doesn't support rxdart v0.25.0

### ISSUE THREAD

**Issue by limoncello** [DarshanGowda0/GeoFlutterFire#138]
`Because geoflutterfire 2.2.1 depends on rxdart ^0.24.1 and no versions of geoflutterfire match >2.2.1 <3.0.0, geoflutterfire ^2.2.1 requires rxdart ^0.24.1.`

**Comment by jonbhanson** [comment]
[Interim solution](https://github.com/DarshanGowda0/GeoFlutterFire/issues/133#issuecomment-762029201)

**Comment by awaik** [comment]
fixed

**Comment by limoncello** [comment]
Because app depends on geoflutterfire ^2.2.2 which depends on rxdart ^0.25.0, rxdart ^0.25.0 is required.
So, because metrolife_app depends on rxdart ^0.26.0, version solving failed.
