### ISSUE TITLE
New Requirement - Support for Flutter Web 

### ISSUE THREAD

**Issue by deepaknssd** [DarshanGowda0/GeoFlutterFire#139]
Team, 
I was not sure whether I can raise this as issue, 

Is there any future scope to support Flutter Web. If this is wrong place to raise new requirement as issue, you can close this.

Thanks,
Deepak

**Comment by awaik** [comment]
Hey @deepaknssd 
we will figure out this possibility within 2 weeks. With the new firestore package, I guess, it could be possible.

**Comment by giorgio79** [comment]
The package works just fine out of the box for flutter web. Using it at cashtic.com

**Comment by awaik** [comment]
Great, also noticed that after the last upgrade it became compatible with web.
Ok. close this issue.
