### ISSUE TITLE
Performing a GeoFire Query on a nested object with array in Flutter

### ISSUE THREAD

**Issue by Beautylivery** [DarshanGowda0/GeoFlutterFire#140]
Hello together,

is it even possible to perform a request on a nested query with array with this lib on a CollectionGroup ?

I try to query for this GeoFirePoint in my DB

![image](https://user-images.githubusercontent.com/49089542/109074544-daed7f80-7732-11eb-8471-8ae22d6dba4a.png)

but i have to admit, struggle with the field to define as well as it contains an array.
Is this the right term for the Stream Setup ?

Stream<List<DocumentSnapshot>> fullServiceCollectionGroup = geo .collection( collectionRef: FirebaseFirestore.instance.collectionGroup('professional')) .within( center: geoPoint, radius: radius, field: 'serviceArea.serviceLocationList.position.geoFirePoint');

Or am i maybe just wrong with my Index ?

![image](https://user-images.githubusercontent.com/49089542/109074564-e345ba80-7732-11eb-8641-43a3ce698984.png)

Hope for your help :)
Thanks a lot

**Comment by Beautylivery** [comment]
I moved my geofire point now first to the documents root.... this helped me with the analysis...

**Comment by awaik** [comment]
Also, Firebase manuals recommend using Maps instead of Lists.
In this case, you have access to the nested objects.
