### ISSUE TITLE
geoflutterfire not compatible with cloud_firestore ^1.0.0

### ISSUE THREAD

**Issue by t-kietzmann** [DarshanGowda0/GeoFlutterFire#141]
Also geoflutterfire needs an update for firestore 1.0.0

**Comment by vishnuagbly** [comment]
#135 fixed this issue, this package is no longer maintained follow this pull request for your issue

**Comment by jonbhanson** [comment]
My null-safe fork can be found [here](https://github.com/jonbhanson/GeoFlutterFire).  It is a work in progress, so please let me know about any problem you run into.

To run it, add to your `pubspec.yaml`:

```yaml
geoflutterfire:
  git: git://github.com/jonbhanson/GeoFlutterFire.git
```

I will publish it to pub.dev soon.

**Comment by vishnuagbly** [comment]
Currently, there are more than 4 forked versions of this library, We are currently thinking to create a single temporary forked or copied version of the repo to work on further development. Anyone who wants to contribute is welcome to join our [Discord Group](https://discord.gg/PWGGgXMv) made for discussion.

**Comment by awaik** [comment]
Hey guys,
I'm happy to take part in a project.
On Saturday I will update dependencies for the latest versions before Flutter 2.0 and null safety features.
Next step we will update the package for null safety. Hope we can do it within 1-2 weeks.
So, Flutter 2 support will be added next 1-2 weeks.
