### ISSUE TITLE
Support flutter 2

### ISSUE THREAD

**Issue by saharvx9** [DarshanGowda0/GeoFlutterFire#142]
Pls support flutter 2 :)

**Comment by vishnuagbly** [comment]
#135 added this support, this repository is no longer maintained, follow that pull request for your issue

**Comment by jonbhanson** [comment]
My null-safe fork can be found [here](https://github.com/jonbhanson/GeoFlutterFire).  It is a work in progress, so please let me know about any problem you run into.

To run it, add to your `pubspec.yaml`:

```yaml
geoflutterfire:
  git: git://github.com/jonbhanson/GeoFlutterFire.git
```

I will publish it to pub.dev soon.

**Comment by wilpar** [comment]
check your rxdart version please, I think it's still the outdated one.  I have other packages which need a newer version.

Cheers for the fork.

**Comment by vishnuagbly** [comment]
Currently, there are more than 4 forked versions of this library, We are currently thinking to create a single temporary forked or copied version of the repo to work on further development. Anyone who wants to contribute is welcome to join our [Discord Group](https://discord.gg/PWGGgXMv) made for discussion.

**Comment by awaik** [comment]
Hey guys,
I'm happy to take part in a project.
On Saturday I will update dependencies for the latest versions before Flutter 2.0 and null safety features.
Next step we will update the package for null safety. Hope we can do it within 1-2 weeks.
So, Flutter 2 support will be added next 1-2 weeks.

**Comment by awaik** [comment]
@jonbhanson Hi! Thank you for your time and support! 
Maybe you would like to make a pull request with null safety or work together on it?

**Comment by jonbhanson** [comment]
@awaik will do. 👍🏻

**Comment by awaik** [comment]
Great! After that, I will go through other issues :)
With the new Firestore web version is working, we should test and document it.
So, awaiting news from you :)

**Comment by awaik** [comment]
Because of @jonbhanson contribution the package already adopted for Flutter 2.x
Now it is available on the branch https://github.com/DarshanGowda0/GeoFlutterFire/tree/3x_null_safety
Next couple of days it will appear on the pub.dev

Everybody welcomes to test and comments or PR's :)

**Comment by awaik** [comment]
Hey guys,

as we discussed https://github.com/DarshanGowda0/GeoFlutterFire/pull/147, now we have 2 branches

1. master
2. 3x_null_safety

Today I made the example app, rewrote the code for the null safety and new Google Maps API.

So, from now on we should create pull requests for these branches.

As @zeusbaba [suggested](https://github.com/DarshanGowda0/GeoFlutterFire/pull/146#issuecomment-792032163) we can create guidelines, it would be great.

And thanks to the community, now we have

<img width="780" alt="Screenshot 2021-03-07 at 12 39 17" src="https://user-images.githubusercontent.com/5330807/110235623-3c3afd00-7f42-11eb-99d3-3a8292041290.png">
