### ISSUE TITLE
When will limit() will be available?

### ISSUE THREAD

**Issue by zphoenixz** [DarshanGowda0/GeoFlutterFire#145]
Hi, there is a pull request which apparently includes limit(), Do you have any plan in including this? For large amount of documents (Very large), AOT it is not scalable.

**Comment by awaik** [comment]
Hi,
yes, now we are working on a new version with null safety. After that, we will add (in case of no bugs) this PR.

**Comment by awaik** [comment]
Hey @zphoenixz 
we added all PR's.
Has the problem solved?

**Comment by zphoenixz** [comment]
Hi guys, I think you missed that one, the guy who created that PR no longer has a GitHub account so his PR got lost in time. However I did clone his repo before that happens, I haven't done that much tests but his limit functionality appears to be working as expected.
PD. I have the limit PR, I can share it with you but I'm afraid that repo is outdated in some other stuff like Null Safety.

**Comment by cngeru** [comment]
I have created a new library that works almost like `GeoFlutterFire` which gives you more control. Please check it out [https://pub.dev/packages/georange](https://pub.dev/packages/georange)
