### ISSUE TITLE
Combining with search leads to cursor errors

### ISSUE THREAD

**Issue by japborst** [DarshanGowda0/GeoFlutterFire#15]
I'm combining search with Geoflutterfire.

For example, when searching for everything that starts with the letter `a`, I can use the following. 

```dart
final Firestore firestore = Firestore.instance;
Query filteredRef = firestore.collection(my_collection')
          .where("query", isGreaterThanOrEqualTo: 'a')
          .where("query", isLessThan: 'b')
          .orderBy("query");

GeoFirePoint location = GeoFirePoint(0, 0);
Stream<List<DocumentSnapshot>> stream = geo
        .collection(collectionRef: filteredRef)
        .within(center: location, radius: 100, field: 'location');
```

However, this leads to the below erorr. I know there are results, so that shouldn't be an issue.
```
com.google.firebase.firestore.FirebaseFirestoreException: INVALID_ARGUMENT: cursor position is outside the range of the original query
```

When using only one filter (e.g. `isEqual` or `isGreaterThanOrEqualTo`) leads to no errors and works.

**Comment by DarshanGowda0** [comment]
Hi @japborst, compound queries with range filters are not supported by cloud firestore as mentioned in the [docs](https://firebase.google.com/docs/firestore/query-data/queries). Also, GeoFlutterFire internally uses `startAt` and `endAt`, so any compound queries that violate rules by firestore when combining with [these](https://github.com/DarshanGowda0/GeoFlutterFire/blob/435a394984006e6c8d5348a50fb47bb7f4230f5a/lib/src/collection.dart#L144) won't work as of now.
