### ISSUE TITLE
Because geoflutterfire >=2.2.2 <3.0.0-nullsafety.1 depends on cloud_firestore ^0.16.0 

### ISSUE THREAD

**Issue by Francmape** [DarshanGowda0/GeoFlutterFire#150]
How solve this, when using both packages.

Because geoflutterfire >=2.2.2 <3.0.0-nullsafety.1 depends on cloud_firestore ^0.16.0 and app depends on cloud_firestore ^1.0.3, geoflutterfire >=2.2.2 <3.0.0-nullsafety.1 is forbidden.

So, because app depends on geoflutterfire ^2.2.2, version solving failed.
pub get failed (1; So, because proximal depends on geoflutterfire ^2.2.2, version solving failed.)
exit code 1

**Comment by awaik** [comment]
Please use null safety version
https://pub.dev/packages/geoflutterfire/versions/3.0.0-nullsafety.2

**Comment by Francmape** [comment]
Hello,
I have. Give the same error.
Find the attached image.

Regards.

**Comment by awaik** [comment]
Can you please:

1. Run `flutter doctor` and paste the output below
2. Run `flutter pub deps -- --style=compact` and paste the output below

**Comment by Francmape** [comment]
Hello,
please find the attached response.
Gives the same error.

**Comment by jemisgoti** [comment]
geoflutterfire 2.2.2 depends on cloud_firestore:0.16.0 and your app uses cloud_firestore ^1.0.3, so you are facing this issue. just replace  cloud_firestore ^1.0.3 with cloud_firestore ^0.16.0 and your problem will be resolve.

**Comment by Francmape** [comment]
Thank you for your reply.
