### ISSUE TITLE
Chinese fonts in iOS app set Locale in Japanese

### ISSUE THREAD

**Issue by ryomoro** [DarshanGowda0/GeoFlutterFire#151]
https://github.com/flutter/flutter/issues/79363#issue-844427700

Version 2.2.1 and 2.1.0 happen this problem.
I build an app Version 2.0.3+8, this issue didn't happen.

**Comment by awaik** [comment]
It looks like the issue with the new Flutter version. Is it correct?

**Comment by ryomoro** [comment]
> It looks like the issue with the new Flutter version. Is it correct?

yes, I think it is.
