### ISSUE TITLE
Because app depends on geoflutterfire ^2.2.2 which depends on rxdart ^0.25.0, rxdart ^0.25.0 is required.

### ISSUE THREAD

**Issue by limoncello** [DarshanGowda0/GeoFlutterFire#152]
Because app depends on geoflutterfire ^2.2.2 which depends on rxdart ^0.25.0, rxdart ^0.25.0 is required.
So, because app depends on rxdart ^0.26.0, version solving failed.

_Originally posted by @limoncello in https://github.com/DarshanGowda0/GeoFlutterFire/issues/138#issuecomment-802784091_

**Comment by awaik** [comment]
Please check https://github.com/DarshanGowda0/GeoFlutterFire/tree/3x_null_safety branch.
Or https://pub.dev/packages/geoflutterfire/versions/3.0.0-nullsafety.2

**Comment by zeusbaba** [comment]
alternatively, you can use `dependency_overrides` in your project.  
For example;  
```  
dependency_overrides:  
  rxdart: ^0.26.0  
```
