### ISSUE TITLE
GeoFlutterFire Alternative With Limits

### ISSUE THREAD

**Issue by cngeru** [DarshanGowda0/GeoFlutterFire#153]
Hello Everyone

I have created a new library that works almost like `GeoFlutterFire` which gives you more control on how you do your queries. Please check it out [https://pub.dev/packages/georange](https://pub.dev/packages/georange)

**Comment by awaik** [comment]
@cngeru Please, do not spam. You have posted about 10 comments with copy-pasted text. It is not ok.

**Comment by cngeru** [comment]
@awaik Noted : Just notifying people who had issues with limiting queries on a new library that makes it easier to do so. 
Kind Regards
