### ISSUE TITLE
geoflutterfire ^2.2.2 which depends on rxdart ^0.25.0, rxdart ^0.25.0 is required. So, because Zero depends on rxdart ^0.27.0, version solving failed.

### ISSUE THREAD

**Issue by devsig** [DarshanGowda0/GeoFlutterFire#155]
geoflutterfire ^2.2.2 which depends on rxdart ^0.25.0, rxdart ^0.25.0 is required.
So, because Zero depends on rxdart ^0.27.0, version solving failed.

**Comment by awaik** [comment]
Solved by https://github.com/DarshanGowda0/GeoFlutterFire/pull/158
