### ISSUE TITLE
How to use GeoFlutterFire like a firestore stream?

### ISSUE THREAD

**Issue by momsenmeister** [DarshanGowda0/GeoFlutterFire#16]
Hi @DarshanGowda0,
first of all, thanks a lot for creating this awesome library!

Unfortunately I have some trouble getting it working the same way like my basic firestore streams.
So far I include my firestore queries directly as a stream in the StreamBuilder widget like this:
`
StreamBuilder(
stream: Firestore.instance.collection('events')
.where("eventTime", isGreaterThanOrEqualTo: DateTime.now().millisecondsSinceEpoch)
.where("eventStatus", isEqualTo: "created")
.orderBy('eventTime').snapshots(),
`
Here, .snapshots() returns a `Stream<QuerySnapshot>`, whereas your example returns a `Stream<List<DocumentSnapshot>>`.

Maybe you could provide an example how to use GeoFlutterFire the same way like the firestore query?
I don't really get the concept of the listener, and your readme says that I should be able to use `geoRef.data()` or `geoRef.snapshot()` to use it the same way like my other streams. I just can't figure out how :-)

Also, if I follow your readme exactly and use the listener, I receive this error:
` com.google.firebase.firestore.FirebaseFirestoreException: INVALID_ARGUMENT: cursor position is outside the range of the original query`

Thanks a lot,
Michael

**Comment by DarshanGowda0** [comment]
Hi @momsenmeister, this should help you :smile:

initialize the stream
```dart
@override
  void initState() {
    super.initState();
    geo = Geoflutterfire();
    var radius = BehaviorSubject(seedValue: 1.0);
    GeoFirePoint center = geo.point(latitude: 12.96, longitude: 77.64);
    stream = radius.switchMap((rad) {
      var collectionReference = _firestore.collection('locations');
      return geo.collection(collectionRef: collectionReference).within(
          center: center, radius: rad, field: 'position', strictMode: true);
    });
  }
```

and you streamBuilder would look like this,
```dart
StreamBuilder(
            stream: stream,
            builder: (BuildContext context,
                AsyncSnapshot<List<DocumentSnapshot>> snapshots) {
              if (snapshots.connectionState == ConnectionState.active &&
                  snapshots.hasData) {
                print('data ${snapshots.data}');
                return Container();
              } else {
                return Center(child: CircularProgressIndicator());
              }
            },
          ),
```

**Comment by momsenmeister** [comment]
Hi @DarshanGowda0,

thanks a lot!
I got it sort of working now if I use a simple query like the one you stated:
`_firestore.collection('locations')`

But I still have two problems left:

1)
It doesn't work when I use a more complex firestore query like this one:
'Firestore.instance.collection('events').where("eventTime", isGreaterThanOrEqualTo: DateTime.now().millisecondsSinceEpoch).where("eventStatus", isEqualTo: "created").orderBy("eventTime");'

I receive the following error and don't get any results from the query:
`com.google.firebase.firestore.FirebaseFirestoreException: INVALID_ARGUMENT: cursor position is outside the range of the original query`.

Maybe that could be due to the restriction of firestore that [doesn't allow queries with range filters on different fields?](https://firebase.google.com/docs/firestore/query-data/queries)

My goal with geoflutterfire was to filter by time (>= now && <= tomorrow) and position (radius < 50) at the same time.

2)
Whenever I add an item to firestore, the stream doesn't properly update.
Instead, the results are just appended to the list, resulting in every item being twice in the list.

**Comment by DarshanGowda0** [comment]
Hey @momsenmeister, yes the problem with (1), as you guessed, is a drawback we have from the cloud_firestore side. As for (2), the issue is fixed in #19.

**Comment by momsenmeister** [comment]
@DarshanGowda0 
Okay, but now I even don't get any results when using:
`Firestore.instance.collection('events').orderBy("eventTime")`
whereas
`Firestore.instance.collection('hoodla-events')` works fine.

So, even the `orderBy` does not work?

**Comment by DarshanGowda0** [comment]
@momsenmeister orderBy is used [internally](https://github.com/DarshanGowda0/GeoFlutterFire/blob/229cdfc82fa027e6ec7dc3e017723a836b69a572/lib/src/collection.dart#L145) in the `within` function, so using another orderBy will mess with the [order](https://firebase.google.com/docs/reference/js/firebase.firestore.Query#startAfter). We could add the `orderBy` after the orderBy of geohash, but that defeats the purpose. You could instead sort it on the client side?

**Comment by momsenmeister** [comment]
@DarshanGowda0 
I see :-)
My use case is to show a list of social events that are filtered by radius but sorted by time.
Initially I tried to filter both on radius and time span, but so far I couldn't find any solution apart from having one filter on the client. But i'll keep trying... I think this issue can be closed than.

Maybe you want to include these two aspects of this issue to your readme?
- queries with range filters on other fields are not possible while using geoflutterfire
- orderBy does not work on the firestore query while using geoflutterfire

Thanks a lot,
Michael

**Comment by DarshanGowda0** [comment]
Yes @momsenmeister, I will include those in the readme.
Thanks 😄

**Comment by lukestokes94** [comment]
Sorry, I'm struggling here with trying to build a list from the above code. I assume I need to build the list within the Container(), but if I try and use a ListBuilder or a toList(), I get errors that they cannot take a <List<DocumentSnapshot>> as a type. My app works fine and I get the print of `data [Instance of 'DocumentSnapshot',` fine, but I just don't see how to access that data (for instance I have other fields such as 'sender' attached to these collections) or build a list (using a list tile or similar) as my goal is to display a list of all collections returned by the geoquery to show all collections within a certain radius of the user. Any help at all would be massively appreciated, please.

```
StreamBuilder(
            stream: stream,
            builder: (BuildContext context,
                AsyncSnapshot<List<DocumentSnapshot>> snapshots) {
              if (snapshots.connectionState == ConnectionState.active &&
                  snapshots.hasData) {
                print('data ${snapshots.data}');
                return Container(
                // List code presumably in here?
                  );
              } else {
                return Center(child: CircularProgressIndicator());
              }
            },
          ),
```

**Comment by smolugu** [comment]
> Hi @momsenmeister, this should help you 😄
> 
> initialize the stream
> 
> ```dart
> @override
>   void initState() {
>     super.initState();
>     geo = Geoflutterfire();
>     var radius = BehaviorSubject(seedValue: 1.0);
>     GeoFirePoint center = geo.point(latitude: 12.96, longitude: 77.64);
>     stream = radius.switchMap((rad) {
>       var collectionReference = _firestore.collection('locations');
>       return geo.collection(collectionRef: collectionReference).within(
>           center: center, radius: rad, field: 'position', strictMode: true);
>     });
>   }
> ```
> 
> and you streamBuilder would look like this,
> 
> ```dart
> StreamBuilder(
>             stream: stream,
>             builder: (BuildContext context,
>                 AsyncSnapshot<List<DocumentSnapshot>> snapshots) {
>               if (snapshots.connectionState == ConnectionState.active &&
>                   snapshots.hasData) {
>                 print('data ${snapshots.data}');
>                 return Container();
>               } else {
>                 return Center(child: CircularProgressIndicator());
>               }
>             },
>           ),
> ```

Hi @DarshanGowda0,
 I am using a simple query to firestore and StreamBuilder, following your example code. I am getting the below error. Can you please tell me what could be causing this?

══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
flutter: The following assertion was thrown building LocationPage(dirty, state:
flutter: _LocationPageState#775f1):
flutter: type '_BroadcastStream<QuerySnapshot>' is not a subtype of type 'Future<QuerySnapshot>'

Regards,
Shyam.

**Comment by reza3322** [comment]
hi guys. and thank you @DarshanGowda0  for the library. 
can anyone help me with this one?
https://stackoverflow.com/questions/61818292/fetching-geopoints-and-setting-markers-on-google-with-flutter

**Comment by saipavankumar-muppalaneni** [comment]
CircularProgressiveIndicator is on forever, and when I used 
//
stream.listen((List<DocumentSnapshot> documentList) {         //Here it throws error 
documentList.forEach( (e) {something}  
})
//
Please brother leave a solution for this, I have been stuck on this for days.
