### ISSUE TITLE
Firestore 3.1.1

### ISSUE THREAD

**Issue by bilalsammour** [DarshanGowda0/GeoFlutterFire#168]
Because `geoflutterfire 3.0.1` depends on `cloud_firestore ^2.3.0` and no versions of `geoflutterfire` match >`3.0.1 <4.0.0`, `geoflutterfire ^3.0.1` requires `cloud_firestore ^2.3.0`.

**Comment by ndpdarshana** [comment]
Any update on this, please?

**Comment by awaik** [comment]
updated with
https://github.com/DarshanGowda0/GeoFlutterFire/pull/170
