### ISSUE TITLE
Update  DarshanGowda0 branch to cloud_firestore: ^3.1.6 and correctly point it in Flutter Pub Dev Doc

### ISSUE THREAD

**Issue by davemg3** [DarshanGowda0/GeoFlutterFire#169]
Currently on 10/01/2022,

The Flutter Pub Dev documentation re-direct to this package https://github.com/xmany/GeoFlutterFire
But the "Pub get" geoflutterfire: ^3.0.1 get the code from  DarshanGowda0 /GeoFlutterFire 3x_null_safety branch

This branch of DarshanGowda0 should  be updated with : 
`cloud_firestore: ^3.1.6`

and clearly pointed out buy Flutter Pub Dev

**Comment by awaik** [comment]
updated with
https://github.com/DarshanGowda0/GeoFlutterFire/pull/170
