### ISSUE TITLE
Empty result when querying "within" on collection

### ISSUE THREAD

**Issue by WieFel** [DarshanGowda0/GeoFlutterFire#191]
Hi,

I am always getting empty results when querying my collection for close documents within 1km.
For being sure, i just created a new collection in my firestore called `test`, with one document which has some hardcoded coordinates.
![image](https://user-images.githubusercontent.com/8345062/178155291-f3475080-7963-4701-9598-c68bd341fc35.png)

In my flutter code, i then query documents in a radius of 1km of that same pair of lat/lon, but I still get an empty result.
```dart
Stream<List<DocumentSnapshot>> get closeDocumentsStream {
    var radius = 1.0; // [km]
    var point = GeoFirePoint(36.723594, -4.4227609);
    return geo.collection(collectionRef: firebaseState.test).within(
          center: point,
          radius: radius,
          field: "position",
        );
  }
```
(where `firebaseState.test` is defined as `get test => _firestore.collection("test");`

Running Flutter `3.0.2` and Dart `2.17.3`, with package versions `geoflutterfire: ^3.0.2` and `cloud_firestore: ^3.1.17`.

Any hints on what I could be doing wrong?

**Comment by bichoalexis** [comment]
I found that is required to use geohash, try it!

**Comment by WieFel** [comment]
@bichoalexis can you give an example? I don't get what you mean exactly...

Just tried
```dart
.within(
        center: point.data,  // added .data
        radius: radius,
        field: "position",
      );
```

but it gives a type error, because `point.data` is no `GeoFirePoint`.

**Comment by bichoalexis** [comment]
I mean, in your Firestore database, when you create a new location, add geohash with geopoints, not just geopoints, then everything will work. By the way, if your are using the latest Firestore version with flutter web, I recommend you to change the dependency to geoflutterfire2. It has more support, this package looks abandoned. :)

**Comment by WieFel** [comment]
@bichoalexis thanks, I already use `geoflutterfire2` now.

But still I don't get it to work. My document looks like this:
<img width="627" alt="image" src="https://user-images.githubusercontent.com/8345062/182726684-63737855-4a22-4a86-ae9a-c5293650dee1.png">

```dart
var radius = 100.0;
var point = geo.point(latitude: 0.0, longitude: 0.0);
return geo.collection(collectionRef: collection).within(
      center: point,
      radius: radius,
      field: "position",
    );
```
Whether I use `position` or `position_hash` as `field`, it doesn't work either...

**Comment by bichoalexis** [comment]
Try to write manually this in your latest document: 
<img width="996" alt="image" src="https://user-images.githubusercontent.com/78701419/182727481-b344e870-1739-411d-a987-903725d1da09.png">

**Comment by WieFel** [comment]
@bichoalexis thank you so much, now I finally got it working!
What I was missing was the correct data structure within firestore.
![immagine](https://user-images.githubusercontent.com/8345062/182839634-721990d9-d65a-4c80-9a6e-bdd8070bfdb2.png)

```dart
geo.collection(collectionRef: collection).within(
      ...
      field: "point",
    );
```
