### ISSUE TITLE
Flutter version solving failed.

### ISSUE THREAD

**Issue by gabilanbrc** [DarshanGowda0/GeoFlutterFire#2]
Hi, im getting 

Because flutter_google_places >=0.1.3 depends on rxdart ^0.19.0 and flutter_google_places <0.1.3 depends on rxdart ^0.18.1, every version of flutter_google_places requires rxdart ^0.18.1 or ^0.19.0.

And because every version of geoflutterfire depends on rxdart ^0.20.0, flutter_google_places is incompatible with geoflutterfire.

So, because XXXX depends on both geoflutterfire ^1.0.2 and flutter_google_places any, version solving failed.
pub get failed (1)
Process finished with exit code 1

Here is my flutter doctor
C:\src\flutter\bin\flutter.bat doctor --verbose
[√] Flutter (Channel master, v1.1.10-pre.200, on Microsoft Windows [VersiÃ³n 6.1.7601], locale es-AR)
    • Flutter version 1.1.10-pre.200 at C:\src\flutter
    • Framework revision 74ebdacad5 (5 hours ago), 2019-01-28 13:07:02 -0500
    • Engine revision 9b6d5031a3
    • Dart version 2.1.1 (build 2.1.1-dev.3.2 a5030ed92f)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\****\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 32.0.1
    • Dart plugin version 182.5124
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.
Process finished with exit code 0

Thanks you in advance

**Comment by DarshanGowda0** [comment]
Hey @gabilanbrc! 
Yes, this issue should be solved once this [pull request](https://github.com/lejard-h/flutter_google_places/pull/43) is merged.

**Comment by DarshanGowda0** [comment]
@comeonbuddy your issue is not related to this thread. This thread is regarding a conflict between rxdart versions of two libraries @gabilanbrc is using.
Your issue is with Dart SDK version, [this](https://github.com/flutter/flutter/issues/27148) provides more info on the same.

**Comment by fliermanrw** [comment]
I have the following version solving error: 

> "Because every version of geoflutterfire depends on cloud_firestore ^0.8.2+3 and dkg_app depends on cloud_firestore ^0.9.0+1, geoflutterfire is forbidden.
> So, because dkg_app depends on geoflutterfire ^1.0.2, version solving failed. ".

Could you please check if it is possible to depend on the latest version?

**Comment by DarshanGowda0** [comment]
@fliermanrw the version has been now upgraded to match all official plugins.

**Comment by mr0kaushik** [comment]
`Because flutter_google_places 0.2.5 depends on rxdart ^0.24.0 and no versions of flutter_google_places match >0.2.5 <0.3.0, flutter_google_places ^0.2.5 requires rxdart ^0.24.0.
`

Is there any thing by which i can solve it ?? 
Thanks

**Comment by Stijnp** [comment]
I'm having a similar issue to mr0kaushik.

Because geoflutterfire >=2.0.3+7 depends on rxdart ^0.23.1 and flutter_google_places 0.2.5 depends on rxdart ^0.24.0, geoflutterfire >=2.0.3+7 is incompatible with flutter_google_places 0.2.5.

Would be great to find a solution to this!

Cheers

**Comment by KBDub** [comment]
I am getting the below error in FlutterFlow...  How do I fix this?  I don't what package brought in the rxdart nor how to remove it.  thanks in advance

 cloud_firestore 4.8.0, every version of geoflutterfire requires rxdart ^0.26.0.
So, because survail_it2 depends on both geoflutterfire any and rxdart 0.27.7, version solving failed.
