### ISSUE TITLE
Question: How to use a where clause?

### ISSUE THREAD

**Issue by udiedrichsen** [DarshanGowda0/GeoFlutterFire#3]
I want to filter the locations for a specific name.

e.g.:
_firestore.collection('locations')
**.where('name',isequalTo: 'hotel')**

Is that possible?

**Comment by DarshanGowda0** [comment]
Hi @udiedrichsen,
Yes, this is possible for `isequalTo` operation as mentioned in the [ReadMe](https://github.com/DarshanGowda0/GeoFlutterFire#scale-to-massive-collections)

**Comment by udiedrichsen** [comment]
Hi, thanks for your fast response. I tried it, but it didnt worked for me.
