### ISSUE TITLE
[Feature Request] Update within() to allow for flat data models

### ISSUE THREAD

**Issue by Carvalho96v2** [DarshanGowda0/GeoFlutterFire#30]
Currently, within() only takes one possible field as the "position" field, however in my use case I have a flat data model (i.e, geohash and geopoint fields are not in their own collection, but are fields within my main collection).

Thus, my data model looks as follows:
User:
 - username
 - email
 - geohash
 - geopoint

As opposed to:
User:
 - username
 - email
 - position:
    - geohash
    - geopoint

Thus, there are 2 separate fields that represent the "position"

I've hacked together my own solution by creating "flat_within" and "_flat_querypoint" methods, which I'll be happy to share and which works for now, but obviously will become an issue as this library grows.

I hope this has been clear :)

**Comment by DarshanGowda0** [comment]
Hi @Carvalho96v2, You could make a copy of geopoint in the outer model as an alternative. But, I'm just trying to understand what's the purpose of making it flat, they both are coupled together as a class in the library. Unless there's a specific advantage in making them flat, I don't think it's a necessity for the library!

**Comment by Carvalho96v2** [comment]
Hey @DarshanGowda0 , the reason why I'd like a flat model is (correct me if I'm wrong), Firestore does not yet support collection group queries, meaning that I can only query a subcollection if I know which parent collection to query in the first place.

This [stackoverflow question](https://stackoverflow.com/questions/46573014/firestore-query-subcollections) explains the use case pretty well.

Do let me know if there is a better workaround that I'm missing :)

**Comment by DarshanGowda0** [comment]
@Carvalho96v2 Yes that's true, but this implementation still doesn't store geopoint/geohash in a subcollection! It's in the same collection stored as a nested object. I think you're confusing nested objects inside firestore documents and subcollections.

**Comment by Carvalho96v2** [comment]
@DarshanGowda0 Whoops, my bad. Thanks for clearing that up! I'll close this issue now :)

Its a great library by the way <3

**Comment by DarshanGowda0** [comment]
Thanks, @Carvalho96v2 😄
