### ISSUE TITLE
[Feature Request] Get a GeoPoint based on the address

### ISSUE THREAD

**Issue by mikeyyg96** [DarshanGowda0/GeoFlutterFire#31]
Is it possible to make this happen? I want the user to be able to input an address to the database that will also create a GeoPoint for that address if it is correct format (address). Or if anyone could point me to a library that already does this would be nice.

**Comment by momoDragon** [comment]
https://pub.dartlang.org/packages/flutter_google_places  Use this to allow users to search address. Then take the lat long from it.
