### ISSUE TITLE
cloud_firestore upgrade to 0.10.x?

### ISSUE THREAD

**Issue by awhitford** [DarshanGowda0/GeoFlutterFire#33]
I ran into a version solving failure because of my dependency: `cloud_firestore: ^0.10.1`

> Because geoflutterfire >=2.0.3 depends on cloud_firestore ^0.9.5+2 and MY_APP depends on cloud_firestore ^0.10.1, geoflutterfire >=2.0.3 is forbidden.
> 
> So, because MY_APP depends on geoflutterfire ^2.0.3+2, version solving failed.

Is it time to update dependencies and cut a new release? 😄

**Comment by awhitford** [comment]
As a workaround, moving `cloud_firestore` to `dependency_overrides` seems to resolve the build issue:
```
dependency_overrides:
  cloud_firestore: ^0.10.1
```

**Comment by theochampion** [comment]
Any update on this, happy to help if migration necessary

**Comment by ebastuart** [comment]
Have the same problem, would be great if it will be adapted to the new version. Thank in advance!

**Comment by DarshanGowda0** [comment]
Will make these changes in a day or two!

**Comment by ebastuart** [comment]
@DarshanGowda0 Awesome, you're the best!

**Comment by DarshanGowda0** [comment]
[2.0.3+3](https://pub.dartlang.org/packages/geoflutterfire) should fix this 😄

**Comment by awhitford** [comment]
I just tried this and it appears to be working great.  Thank you for the quick response.
