### ISSUE TITLE
arrayContains causes exception

### ISSUE THREAD

**Issue by mikeyyg96** [DarshanGowda0/GeoFlutterFire#34]
It doesn't seem to be working for me. I get PlatformException:
`PlatformException (PlatformException(error, Invalid Query. Queries only support having a single array-contains filter., null))`

` var queryRef = _firestore.collection('events')
    .where('category', arrayContains: acceptedCategories)
    .where('organizer', arrayContains: acceptedOrganizers);`

acceptedCategories & acceptedOrganizers are both lists.

`var acceptedCategories = ["Casual", "Food", "Activites"]`
`var acceptedOrganizers = ["Non-Trusted", "Verified"]`

**Comment by DarshanGowda0** [comment]
Hey @mikeyyg96, this seems to be a cloud_firestore limitation in general, not an issue related to this library. Check this out for more details - [https://stackoverflow.com/a/53096359/3860386](https://stackoverflow.com/a/53096359/3860386)
