### ISSUE TITLE
Version issue 

### ISSUE THREAD

**Issue by momoDragon** [DarshanGowda0/GeoFlutterFire#44]
Error: 
Because geoflutterfire 2.0.3+4 depends on cloud_firestore ^0.11.0+1 and food_plus_life depends on cloud_firestore 0.12.1, geoflutterfire 2.0.3+4 is forbidden.

**Comment by momoDragon** [comment]
@DarshanGowda0  could u please update ?

**Comment by JonasTillges** [comment]
@momoDragon #45

**Comment by DarshanGowda0** [comment]
Thank you @JonasTillges! fixed in [2.0.3+5](https://pub.dev/packages/geoflutterfire)
