### ISSUE TITLE
Radius not properly working

### ISSUE THREAD

**Issue by jchapuy** [DarshanGowda0/GeoFlutterFire#46]
Hi !

I have an issue with the radius : if I choose a radius of 2, even documents within a radius of 8 are returned. 

And when I enter a radius bigger then 5, all documents within a radius of 60 are returned.

```
Stream<List<DocumentSnapshot>> stream = geo.collection(collectionRef: collectionReference)
                                        .within(center: center, radius: 2.0, field: field);
    stream.listen((List<DocumentSnapshot> documentList) {
      documentList.forEach((DocumentSnapshot document) {
        // ...
      });
    });
  }
```

I also tried using RXDart but the problem remains
```
var radius = BehaviorSubject<double>.seeded(1.0);
var collectionReference = _firestore.collection('locations');

stream = radius.switchMap((rad) {
      return geo
          .collection(collectionRef: collectionReference)
          .within(center: center, radius: rad, field: 'position');
    });
```

Any idea on how to solve this ?

Thanks for your amazing work !

**Comment by DarshanGowda0** [comment]
Hey @jchapuy! Check out [this](https://github.com/DarshanGowda0/GeoFlutterFire#performing-geo-queries), use strictMode for filtering strictly based on radius! The limitation is due to the rectangle shape of geo-hashes!

**Comment by jchapuy** [comment]
Sorry I did not noticed it on the documentation. It now works. Thank you !
