### ISSUE TITLE
[Question] Limit and orderBy limitations

### ISSUE THREAD

**Issue by VictorUvarov** [DarshanGowda0/GeoFlutterFire#54]
I've read that this plugin does not support limit() and orderBy() chaining on within().
However, does the plugin support the reference to do the limit() and orderBy() work?
Example: 
```dart
    final ref = _instance
        .collection(collectionName)
        .orderBy(field, descending: true)
        .limit(limit);

    Geoflutterfire().collection(collectionRef: ref);
```
I'm getting mixed results coming back from the stream.

**Comment by joknjokn** [comment]
Did you find a way to limit?

**Comment by VictorUvarov** [comment]
The package does not support the feature. I moved on.

**Comment by rdev-software** [comment]
But what about paging in general. As per documentation collection is sorted by distance. Cant we at least get paging in place? 

So lets say that I set radius to 1000km, and this will produce 500 entries. Cant we just limit it to 50 and get last document and then call startAt ?!

**Comment by davydany** [comment]
> The package does not support the feature. I moved on.

@VictorUvarov What did you move on to?
