### ISSUE TITLE
How GeoFlutterFire works

### ISSUE THREAD

**Issue by DavidCorrado** [DarshanGowda0/GeoFlutterFire#6]
Might be useful to describe technically how this library works as it will help people make the decision to use this library.  From my understanding this is how it works:

**Geohash technical details**
The library generates a 9 character geohash based off the lat long.  This hashcode defines a rectangular box which is accurate within 5 meters you can see [here](https://www.movable-type.co.uk/scripts/geohash.html)

Based on the radius you send when doing Geo-Queries we reduce the number of characters in the geohash which increases the size of the rectangular box that covers the radius given above. We run the query based on that shortened geohash on the server side.  Then locally we filters out data based on the circle generated by the radius.

**Note:**
Knowing that this library mostly runs on the server side makes this library be a big win which is not as clear from the description.

Once again thanks for all the work.

**Comment by DarshanGowda0** [comment]
Hi @DavidCorrado, yes your description pretty much covers it.
The library was heavily influenced by [GeoFireX](https://github.com/codediodeio/geofirex) which has a brief technical explanation with a [tutorial](https://angularfirebase.com/lessons/geolocation-query-in-firestore-realtime/). 
Also, there's gonna be a small article/video from [fireship](https://fireship.io/) regarding GeoFlutterFire soon.
