### ISSUE TITLE
cloud_firestore 0.13.0 compatible

### ISSUE THREAD

**Issue by awhitford** [DarshanGowda0/GeoFlutterFire#65]
Now that `cloud_firestore 0.13` has been released, one will run into a problem trying to use it with `geoflutterfire`; `flutter pub get` returns something like this:
> Because geoflutterfire 2.0.3+5 depends on cloud_firestore ^0.12.5 and no versions of geoflutterfire match >2.0.3+5 <3.0.0, geoflutterfire ^2.0.3+5 requires cloud_firestore ^0.12.5.

Please, we could use an upgrade. 😄

**Comment by awhitford** [comment]
It looks like someone already has a pull request:  https://github.com/DarshanGowda0/GeoFlutterFire/pull/64

**Comment by DarshanGowda0** [comment]
Fixed as of #67
