### ISSUE TITLE
No distance field bundled in with .data

### ISSUE THREAD

**Issue by Sam-Guru-In-Training** [DarshanGowda0/GeoFlutterFire#87]
Yes, doesn't appear to be passed in, I'm having to use the Utility method .distance on the GeoFire object.  Would be much cooler to just have it there with the snapshot data.

**Comment by Sam-Guru-In-Training** [comment]
Ah, error with getting usersLocation from SharedPRefs, my bad.  Sorry for your attention

**Comment by webertim** [comment]
Same issue here. After having a quick look at the source code it seems pretty wasted to call the distance method again, since it is already called in the 'within' method. Would be great to have another within method which returns a Stream of DistanceDocumentSnapshots right away.

**Comment by RodoHS** [comment]
@DarshanGowda0 will @webertim 's pull request be merged anytime soon? would be nice to have access to the distance parameter as standard in this package. Thank you

**Comment by giorgio79** [comment]
Patch works great for me @DarshanGowda0

**Comment by Stijnp** [comment]
Also very keen on this feature!

**Comment by awaik** [comment]
In the version https://pub.dev/packages/geoflutterfire/versions/3.0.0-nullsafety.2 it should work.
