### ISSUE TITLE
Version not supported by form_bloc

### ISSUE THREAD

**Issue by NestorDevs** [DarshanGowda0/GeoFlutterFire#90]
I am working with form_bloc and this plugins presents the following problem: form_bloc uses rxdart 0.24 and your plugins uses a lower version so it presents an error when installing the dependencies. when are you planning to update the plugins?

**Comment by awhitford** [comment]
+1 -- Me too for an upgrade.

Workaround is to use `dependency_overrides`, but that can get a little risky if there is a breaking change.

**Comment by awaik** [comment]
upgraded with https://github.com/DarshanGowda0/GeoFlutterFire/pull/170
