### ISSUE TITLE
Distance Calculation Returning incorrect value

### ISSUE THREAD

**Issue by colmmurphy91** [DarshanGowda0/GeoFlutterFire#96]
I/flutter (11893): from document lat 25.1886493 + long 55.2978295
I/flutter (11893): from center lat  25.1875867 +  long 55.2988667
I/flutter (11893): distance = 3021.867

when calculated from link below here I see distance as 0.1576

https://www.movable-type.co.uk/scripts/latlong.html?from=25.1886493,55.2978295&to=25.1875867,55.2988667

**Comment by colmmurphy91** [comment]
@DarshanGowda0 please take a look

**Comment by webertim** [comment]
@colmmurphy91 When I calculate it like this:
`GeoFirePoint(25.1886493, 55.2978295).distance(lat: 25.1875867, lng: 55.2988667).toString()`
I get 0.158. So this seems to be an issue on your side.

**Comment by colmmurphy91** [comment]
thank you very much for sharing the example, i now have it working in my code. Thanks for the quick response
